name: admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  graphql_flutter: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  fl_chart: ^0.68.0
  intl: ^0.17.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/